source 'http://www.rubygems.org'

gem 'sinatra'
gem 'haml'
gem 'activerecord', require: 'active_record'
gem 'rake'
gem 'sqlite3'
gem 'shotgun'
gem 'require_all'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rack-flash3', require: 'rack-flash'
gem 'rack-test'
gem 'minitest', '~> 5.14', '>= 5.14.2'
gem 'pry', '~> 0.13.1'
